apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech365
  labels:
    app: tech365
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech365
  template:
    metadata:
      labels:
        app: tech365
    spec:
      containers:
      - name: tech365
        image: 222634367210.dkr.ecr.us-east-1.amazonaws.com/tech365app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: tech365
    k8-app: tech365
  name: tech365
spec:
  selector:
    app: tech365
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer